"""initial migration

Revision ID: 6eaca6180933
Revises: b6471fb81b6f
Create Date: 2021-03-17 23:00:43.366544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eaca6180933'
down_revision = 'b6471fb81b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.drop_column('roles', 'permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permission', sa.INTEGER(), nullable=True))
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###
